[build]
builder = "nixpacks"

[deploy]
startCommand = "gunicorn app:app --timeout 600"
releaseCommand = "python3 setup_data.py --users 10000"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
